### ISSUE TITLE
Redundant decoding in CategoryListColumn

### ISSUE THREAD

**Issue by lalithsuresh** [vmware/hillview#228]
Every sketch performs an isMissing() check on each row of a column before accessing it with say, getString().

CategoryListColumn implements isMissing() as "return getString() == null". This in turn leads to getString() being invoked twice per row, which is redundant. getString() itself has the custom lookup steps with the segments, some condition checking, and is followed by the decoding step which in turn invokes a hash table lookup. Avoiding this redundancy will shave off up to 10% of the overall runtime for a histogram.

BaseArrayColumn and BaseListColumn track missing entries using a BitSet. This makes isMissing() cheaper than the subsequent decoding when calling asString(). Why aren't we using that approach for CategoryListColumn?

**Comment by mbudiu-vmw** [comment]
The BitSet requires extra storage.
We no longer have CategoryListColumn; it has been folded into StringListColumn.
I will close this issue; performance seems to be adequate.
