### ISSUE TITLE
There is a race in websockets on the server side

### ISSUE THREAD

**Issue by mbudiu-vmw** [vmware/hillview#282]
This causes the server to drop the connection early with an error message.

**Comment by mbudiu-vmw** [comment]
@lalithsuresh : I have pushed the fix you suggested. No races so far. Keeping fingers crossed.

**Comment by lalithsuresh** [comment]
Did you also merge the shared ELG and executor patches for RemoteDataSet?

**Comment by mbudiu-vmw** [comment]
Probably not...

**Comment by mbudiu-vmw** [comment]
Can you submit a PR so I don't have to fish the stuff out from a branch?

**Comment by mbudiu-vmw** [comment]
Maybe I did, the diff is empty.
