### ISSUE TITLE
Significant Digit displays inconsistent?

### ISSUE THREAD

**Issue by parikg** [vmware/hillview#297]
![digit](https://user-images.githubusercontent.com/22647534/36820716-2497dc9e-1ca4-11e8-9e95-333feee9f568.png)

Is there a reason why the last row count looks different from the rest.

**Comment by mbudiu-vmw** [comment]
What is the difference?

**Comment by parikg** [comment]
5.03K is written as an approximate number. This is an integer so it is something 4 digits long, say 5031. Then shouldn't 4993 be written as 4.99K?

**Comment by mbudiu-vmw** [comment]
We avoid shortening 4-digits number less than 5000 because sometimes these can be years, and in general you don't want to abbreviate a year.  Interestingly, 4993 uses fewer symbols than 5.03K.

**Comment by parikg** [comment]
Why dont we start the K notation at  5 digits.

P.
