### ISSUE TITLE
stop.py + start.py does not restart cluster

### ISSUE THREAD

**Issue by lalithsuresh** [vmware/hillview#383]
We've been running into issues where some backend servers crash after a while (I can't figure out why). Doing stop.py + start.py does not restart all the servers. It needs multiple iterations at times to get the entire cluster running.

**Comment by mbudiu-vmw** [comment]
I have made the start script more robust: it will check if the starting of the service failed immediately.
I have added a new script called status.py which will check whether the service is running.
