### ISSUE TITLE
AssertionError while deploying Hillview

### ISSUE THREAD

**Issue by SivaMaplelabs** [vmware/hillview#398]
root@siva:~/SIVA/hillview/bin# python deploy.py config.json
('Importing configuration from', 'config.json')

('Preparing web server', u'localhost')
Creating web service folder

Traceback (most recent call last):
  File "deploy.py", line 84, in <module>
    main()
  File "deploy.py", line 80, in main
    prepare_webserver(config)
  File "deploy.py", line 20, in prepare_webserver
    rh = RemoteHost(config.user, config.webserver)
  File "/root/SIVA/hillview/bin/hillviewCommon.py", line 83, in __init__
    assert isinstance(user, str)
AssertionError

**Comment by SivaMaplelabs** [comment]
The reason for the AssertionError is the type of the user is Unicode(https://github.com/vmware/hillview/blob/master/bin/deploy.py#L15)

**Comment by mbudiu-vmw** [comment]
My guess is that you are using python2 instead of python3.

**Comment by SivaMaplelabs** [comment]
Oops... Yeah, I was using python2. 
@mbudiu-vmw Please close this issue.  In python3 type is 'str' only.
