### ISSUE TITLE
install-dependencies.sh does not work correctly on Ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by SivaMaplelabs** [vmware/hillview#406]
root@pndademocloud-logserver:~/hillview/hillview/bin# ./install-dependencies.sh
Installing programs needed to build
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'nodejs' instead of 'nodejs-legacy'
Note, selecting 'nodejs' instead of 'npm'
E: Unable to locate package maven
E: Unable to locate package libgfortran3

**Comment by SivaMaplelabs** [comment]
Able to deploy Hillview after installing the dependencies manually and changing the loader path https://github.com/vmware/hillview/blob/master/web/src/main/webapp/webpack.config.js#L34 to "/usr/lib/node_modules/ts-loader"

**Comment by SivaMaplelabs** [comment]
# install maven
cd /usr/local
wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
sudo tar xzf apache-maven-3.5.4-bin.tar.gz
sudo ln -s apache-maven-3.5.4 apache-maven
echo "JAVA_HOME=/usr/lib/jvm/java-8-oracle" >> /etc/environment
echo "M2_HOME=/usr/local/apache-maven" >> /etc/environment
echo "MAVEN_HOME=/usr/local/apache-maven" >> /etc/environment
echo "PATH=${M2_HOME}/bin:${PATH}" >> /etc/environment
source /etc/environment

# install nodejs
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by mbudiu-vmw** [comment]
I am not sure we want to implement all this stuff to support relatively old platforms; this becomes a very complicated process. If people do not have a more recent ubuntu they will probably have to fallback on manual installation.

**Comment by SivaMaplelabs** [comment]
Sure.

**Comment by SivaMaplelabs** [comment]
Closing this issue as it is occurring in old platform.
