### ISSUE TITLE
Maximize the view not working

### ISSUE THREAD

**Issue by SivaMaplelabs** [vmware/hillview#409]
Steps to reproduce
1. Generate some error(io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
)
2. Minimize the view
3. Maximize the view

**Comment by SivaMaplelabs** [comment]
![hillview-2](https://user-images.githubusercontent.com/22631594/45541195-05ca0e80-b82c-11e8-803c-70d39a7fa0e7.PNG)

**Comment by mbudiu-vmw** [comment]
I am not sure how you are generating an error.
What was in the view when you minimized it?

**Comment by SivaMaplelabs** [comment]
![hillview-1](https://user-images.githubusercontent.com/22631594/45583117-c2c67480-b8d9-11e8-9652-8d1600af43db.PNG)

**Comment by SivaMaplelabs** [comment]
Have changed the fileNamePattern to generate the error(https://github.com/vmware/hillview/blob/master/web/src/main/java/org/hillview/targets/InitialObjectTarget.java#L113)

**Comment by mbudiu-vmw** [comment]
BTW: if you get this error it usually means that the two jars are not built from the same version of the code. You should rebuild both.

**Comment by mbudiu-vmw** [comment]
Indeed, error messages are not preserved when minimizing/maximizing.
