### ISSUE TITLE
Hillview backend workers are not getting started in Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by SivaMaplelabs** [vmware/hillview#413]
**Root node log**
Starting web server hillview-root
On hillview-root : export WEB_CLUSTER_DESCRIPTOR=serverlist; cd /root/hillview; nohup apache-tomcat-9.0.4/bin/startup.sh &
Tomcat started.
Starting backend hillview-leaf-1
On hillview-leaf-1 : cd /root/hillview/hillview; nohup java -Dlog4j.configurationFile=./log4j.properties -server -Xms25G -Xmx25G -Xloggc:/root/hillview/hillview/gc.log -jar /root/hillview/hillview/hillview-server-jar-with-dependencies.jar 0.0.0.0:3569 >nohup.out 2>&1 &
On hillview-leaf-1 : if pgrep -f hillview-server; then echo Started; else  echo "Could not start hillview on hillview-leaf-1";  cat /root/hillview/hillview/nohup.out; false; fi
2594
Started
Starting backend hillview-leaf-2
On hillview-leaf-2 : cd /root/hillview/hillview; nohup java -Dlog4j.configurationFile=./log4j.properties -server -Xms25G -Xmx25G -Xloggc:/root/hillview/hillview/gc.log -jar /root/hillview/hillview/hillview-server-jar-with-dependencies.jar 0.0.0.0:3569 >nohup.out 2>&1 &
On hillview-leaf-2 : if pgrep -f hillview-server; then echo Started; else  echo "Could not start hillview on hillview-leaf-2";  cat /root/hillview/hillview/nohup.out; false; fi
1838
Started

**Worker node log**

root@hillview-leaf-1:~/hillview/hillview# ps -ef | grep hillview-server
root      2640  1577  0 06:14 pts/0    00:00:00 grep --color=auto hillview-server
root@hillview-leaf-1:~/hillview/hillview#
root@hillview-leaf-1:~/hillview/hillview# netstat -tnlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1146/sshd
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      1383/master
tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      1135/named
tcp        0      0 0.0.0.0:110             0.0.0.0:*               LISTEN      1240/dovecot
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN      1240/dovecot
tcp        0      0 10.11.0.78:53           0.0.0.0:*               LISTEN      1135/named
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      1135/named
tcp6       0      0 :::22                   :::*                    LISTEN      1146/sshd
tcp6       0      0 :::25                   :::*                    LISTEN      1383/master
tcp6       0      0 ::1:953                 :::*                    LISTEN      1135/named
tcp6       0      0 :::110                  :::*                    LISTEN      1240/dovecot
tcp6       0      0 :::143                  :::*                    LISTEN      1240/dovecot
tcp6       0      0 :::53                   :::*                    LISTEN      1135/named

In the log, it is showing as "Started" even though backed workers not started.

**Comment by mbudiu-vmw** [comment]
There isn't enough information in this report to diagnose and reproduce the problem.
What the start script does it to essentially execute this command on every host:
```
java -Dlog4j.configurationFile=./log4j.properties -server -Xms25G -Xmx25G -Xloggc:/root/hillview/hillview/gc.log -jar /root/hillview/hillview/hillview-server-jar-with-dependencies.jar 0.0.0.0:3569
```

What happens when you do this manually on a host?
Do your machines have enough memory for the 25G heap size you have specified in the config file?
