### ISSUE TITLE
Generic logs table schema not preserving the order log format schema

### ISSUE THREAD

**Issue by SivaMaplelabs** [vmware/hillview#445]
If the log format is %{TIMESTAMP:Time} %{LEVEL:Level} %{DATA:Message}
The schema in the Hillview table should be like  - Time Level Message
Currently, it is displaying like - Level Message Time.

**Comment by mbudiu-vmw** [comment]
I don't understand this issue.

**Comment by SivaMaplelabs** [comment]
Have raised the PR in the java-grok.
PR approved.
https://github.com/thekrakken/java-grok/pull/106

**Comment by mbudiu-vmw** [comment]
So this is an issue with grok.
You can probably sidestep by keeping the schema explicitly in the parser and scanning the key-value pairs in the order of the schema.

**Comment by mbudiu-vmw** [comment]
This issue should have been fixed in PR #482
