### ISSUE TITLE
No flexibility to enter the value in the drop-down box

### ISSUE THREAD

**Issue by SivaMaplelabs** [vmware/hillview#446]
Currently, there is no flexibility to enter the value in the drop-down box except choosing the values.

![drop-down-box](https://user-images.githubusercontent.com/22631594/46715005-c43a5100-cc7b-11e8-8db0-53207520e2ec.PNG)

**Comment by mbudiu-vmw** [comment]
The drop-down you are showing selects a column.
You enter the value in the box after that.

**Comment by SivaMaplelabs** [comment]
The issue refers to the flexibility to enter the Column name along with selecting from the drop-down.

**Comment by mbudiu-vmw** [comment]
We actually use a standard html select element: https://www.w3schools.com/tags/tag_select.asp
I assume you want to type a column name, but not search for it?
Do you know an html element which does this?

**Comment by CMADHANKUMAR** [comment]
@mbudiu-vmw We can use DataList instead of DropDownList.

![screenshot 77](https://user-images.githubusercontent.com/33177282/50588537-98102400-0ea8-11e9-9ebc-a89f020dd2c1.png)

Please let me know your views on the same. Will start working on this issue.

**Comment by mbudiu-vmw** [comment]
Sounds great.

**Comment by mbudiu-vmw** [comment]
Is datalist supported on safari?

**Comment by SivaMaplelabs** [comment]
@mbudiu-vmw Looks like Datalist elements are not supported in Safari.
https://stackoverflow.com/questions/27494084/html5-datalist-tag-is-not-populating-in-safari
