### ISSUE TITLE
Many "Could not find subscription" warnings in the Hillview logs

### ISSUE THREAD

**Issue by SivaMaplelabs** [vmware/hillview#447]
![warnings](https://user-images.githubusercontent.com/22631594/46735532-11d2b000-ccb4-11e8-9f41-69e78d009f19.PNG)

**Comment by mbudiu-vmw** [comment]
I will change these to be info instead of warning.

**Comment by SivaMaplelabs** [comment]
Fixed by https://github.com/vmware/hillview/commit/5dcf717b9c303a51714f91a1a0e728e004c15eb2
