### ISSUE TITLE
Support hillview on RedHat/CentOS too

### ISSUE THREAD

**Issue by SivaMaplelabs** [vmware/hillview#450]

**Comment by mbudiu-vmw** [comment]
We don't have resources to test on these systems.
What do you expect is different from Ubuntu?
I expect all differences are in the *build* process. I have successfully run Hillview on Windows. So if you build the jars and war on some system you should be able to run them anywhere.

**Comment by SivaMaplelabs** [comment]
Yeah, it would good to support Hillview to deploy on other Linux distributions too.
We are working on this. Will submit the PR soon.
Changes are required to install dependencies.
