### ISSUE TITLE
Arguments filter not working properly

### ISSUE THREAD

**Issue by SivaMaplelabs** [vmware/hillview#454]
![f3](https://user-images.githubusercontent.com/22631594/46865308-b3840980-ce3a-11e8-8bb6-05fd396f55c3.PNG)

**Comment by SivaMaplelabs** [comment]
Without match returning the records.

**Comment by mbudiu-vmw** [comment]
I don't understand exactly what the problem is here.

**Comment by SivaMaplelabs** [comment]
It is filtering 2 records even though there is no value for the find field.

**Comment by mbudiu-vmw** [comment]
It looks like you search for empty arguments, and you get the empty arguments.
That looks like a legal search.

**Comment by SivaMaplelabs** [comment]
@mbudiu-vmw It should not retrieve the records with empty arguments. But currently,
![f21](https://user-images.githubusercontent.com/22631594/47555607-dc6fc880-d929-11e8-8e89-b2a4030b5007.PNG)
 it is showing all the records.

**Comment by SivaMaplelabs** [comment]
For other empty columns, it is retrieving zero records.

![f22](https://user-images.githubusercontent.com/22631594/47555715-25c01800-d92a-11e8-9544-e83e673d6d78.PNG)

**Comment by mbudiu-vmw** [comment]
I could not reproduce this problem. The "class" column never has empty values.
