### ISSUE TITLE
Filter with time not working

### ISSUE THREAD

**Issue by SivaMaplelabs** [vmware/hillview#455]
![f4](https://user-images.githubusercontent.com/22631594/46865887-c7c90600-ce3c-11e8-99d0-f28f19040dc6.PNG)

**Comment by mbudiu-vmw** [comment]
This is really a duplicate of #411.

**Comment by SivaMaplelabs** [comment]
Closing this as it is a duplicate of https://github.com/vmware/hillview/issues/411
