### ISSUE TITLE
RFC5424 and Startup logs needs to be added to sample_logs folder

### ISSUE THREAD

**Issue by arvind008** [vmware/hillview#487]
sample_logs folder does not have RFC5424 and Startup logs.
GenericLogs Test case throws and Error.

**Comment by SivaMaplelabs** [comment]
https://github.com/vmware/hillview/blob/master/platform/src/test/java/org/hillview/test/storage/GenericLogsTest.java#L230
https://github.com/vmware/hillview/blob/master/platform/src/test/java/org/hillview/test/storage/GenericLogsTest.java#L162
