### ISSUE TITLE
ConfigGrammarTest throws an error for "web.server.name"

### ISSUE THREAD

**Issue by arvind008** [vmware/hillview#488]
ConfigGrammarTest fails with an error: 

> ConfigGrammarTest.testConfigLoading:35 expected:<[web.server.name]> but was:<[localhost]>

The test case fails for ConfigGrammarTest class when we configure config.json file with "web.server.name" as hostname or ip.

**Comment by SivaMaplelabs** [comment]
It will fail not only the above case but also the following cases.

        Assert.assertEquals("web.server.name", config.webserver);
            >>> root node name need not be "web.server.name"

        Assert.assertEquals(4, workers.size());
            >>> Number of worker nodes need not be 4. If the user increase/decrease the worker nodes, 
                   the test case will fail.

        Assert.assertEquals(2, config.aggregators.length);
            >>> Number of aggregator nodes need not be 2. If the user increase/decrease the aggregator 
                    nodes, the test case will fail.

        Assert.assertEquals("worker1.name", workers.get(0).host);
            >>> worker node name need not be "worker1.name"

        Assert.assertEquals("/home/hillview", config.service_folder);
            >>> If users change the service directory, the test case will fail.

**Comment by mbudiu-vmw** [comment]
Do not change the config.json file; create new ones if you need.

**Comment by SivaMaplelabs** [comment]
It would be good if we document the same.
