### ISSUE TITLE
Drag to filter histogram doesn't work

### ISSUE THREAD

**Issue by daniarherikurniawan** [vmware/hillview#678]
I have the tab bookmarked below, and I failed to do a filter (with mouse drag) on the histogram in the last window. I am trying to filter the data for a specific timestamp like this:
![image](https://user-images.githubusercontent.com/7077197/91775414-9c766e00-ebb0-11ea-9d49-e537c8e2fede.png)

However the result is just `No non-missing data`. Is this behavior expected? Perhaps I do the drag incorrectly.

http://cass-1.cassandra-mitmem.cs331-uc.emulab.net:8080?bookmark=11f3b33b-931d-4c23-a2e3-d34c0319376c.json

**Comment by mbudiu-vmw** [comment]
This may be a bug related to the timezone; I am guessing that I am incorrectly passing a different timezone to the back-end.
So it looks like a real bug.
