### ISSUE TITLE
The charts menu may be shown out of the screen.

### ISSUE THREAD

**Issue by mbudiu-vmw** [vmware/hillview#680]
![image](https://user-images.githubusercontent.com/19397042/91919497-09eed100-ec7b-11ea-8772-ee11c457e818.png)

**Comment by mbudiu-vmw** [comment]
If it is too close to the right margin the menu should popup on the left instead.

**Comment by daniarherikurniawan** [comment]
Okay, I will address this bug

**Comment by mbudiu-vmw** [comment]
Fixed in #690
